server:
  port: 8091
#MySQL 연결하기
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: 1111
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  sql:
    init:
      mode: always


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
#      validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect